/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddStorage: typeof import('./components/AddStorage.vue')['default']
    BaseFooter: typeof import('./components/BaseFooter.vue')['default']
    ChooseFood: typeof import('./components/ChooseFood.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    DishTag: typeof import('./components/tags/DishTag.vue')['default']
    EditStorage: typeof import('./components/EditStorage.vue')['default']
    InstallPwa: typeof import('./components/InstallPwa.vue')['default']
    MeatTag: typeof import('./components/tags/MeatTag.vue')['default']
    Menu: typeof import('./components/Menu.vue')['default']
    README: typeof import('./components/README.md')['default']
    ReloadPrompt: typeof import('./components/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFoodInput: typeof import('./components/SearchFoodInput.vue')['default']
    StapleTag: typeof import('./components/tags/StapleTag.vue')['default']
    StorageItem: typeof import('./components/StorageItem.vue')['default']
    StorageList: typeof import('./components/StorageList.vue')['default']
    Switch: typeof import('./components/Switch.vue')['default']
    ToggleMode: typeof import('./components/ToggleMode.vue')['default']
    ToolTag: typeof import('./components/tags/ToolTag.vue')['default']
    VanActionBar: typeof import('vant/es')['ActionBar']
    VanActionBarButton: typeof import('vant/es')['ActionBarButton']
    VanActionBarIcon: typeof import('vant/es')['ActionBarIcon']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanCascader: typeof import('vant/es')['Cascader']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanDivider: typeof import('vant/es')['Divider']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanProgress: typeof import('vant/es')['Progress']
    VanTag: typeof import('vant/es')['Tag']
    VegetableTag: typeof import('./components/tags/VegetableTag.vue')['default']
    WrapperMd: typeof import('./components/WrapperMd.vue')['default']
  }
}
