/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutMe: typeof import('./components/AboutMe.vue')['default']
    AddStorage: typeof import('./components/AddStorage.vue')['default']
    BaseFooter: typeof import('./components/BaseFooter.vue')['default']
    ChooseFood: typeof import('./components/ChooseFood.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    DishTag: typeof import('./components/tags/DishTag.vue')['default']
    EditStorage: typeof import('./components/EditStorage.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCheckTag: typeof import('element-plus/es')['ElCheckTag']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    InstallPwa: typeof import('./components/InstallPwa.vue')['default']
    MeatTag: typeof import('./components/tags/MeatTag.vue')['default']
    Menu: typeof import('./components/Menu.vue')['default']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutCell: typeof import('@nutui/nutui')['Cell']
    NutEmpty: typeof import('@nutui/nutui')['Empty']
    NutMenu: typeof import('@nutui/nutui')['Menu']
    NutMenuItem: typeof import('@nutui/nutui')['MenuItem']
    NutSearchbar: typeof import('@nutui/nutui')['Searchbar']
    README: typeof import('./components/README.md')['default']
    ReloadPrompt: typeof import('./components/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFoodInput: typeof import('./components/SearchFoodInput.vue')['default']
    StapleTag: typeof import('./components/tags/StapleTag.vue')['default']
    StorageList: typeof import('./components/StorageList.vue')['default']
    Switch: typeof import('./components/Switch.vue')['default']
    ToggleMode: typeof import('./components/ToggleMode.vue')['default']
    ToolTag: typeof import('./components/tags/ToolTag.vue')['default']
    VegetableTag: typeof import('./components/tags/VegetableTag.vue')['default']
    WrapperMd: typeof import('./components/WrapperMd.vue')['default']
  }
}
